export const DEWEY_CLASSES = [
  { code: '000', label: 'GENERAL WORKS' },
  { code: '020', label: 'Library and Information Science' },
  { code: '030', label: 'General Encyclopedias' },
  { code: '050', label: 'General Periodicals' },
  { code: '060', label: 'General Organizations' },
  { code: '100', label: 'PHILOSOPHY' },
  { code: '110', label: 'Metaphysics' },
  { code: '130', label: 'Psychology, occultism' },
  { code: '140', label: 'Philosophy' },
  { code: '150', label: 'Psychology' },
  { code: '160', label: 'Logic' },
  { code: '200', label: 'RELIGION' },
  { code: '220', label: 'The Bible' },
  { code: '230', label: 'Christian Doctrine' },
  { code: '290', label: 'Comparative and Other Religions' },
  { code: '300', label: 'SOCIAL SCIENCES' },
  { code: '310', label: 'Statistics' },
  { code: '320', label: 'Political Science' },
  { code: '330', label: 'Economics' },
  { code: '340', label: 'Law' },
  { code: '350', label: 'Public Administration' },
  { code: '360', label: 'Social Welfare' },
  { code: '370', label: 'Education' },
  { code: '380', label: 'Public Service' },
  { code: '390', label: 'Customs and Folklore' },
  { code: '400', label: 'LANGUAGE' },
  { code: '410', label: 'Comparative Linguistics' },
  { code: '420', label: 'English and Anglo Saxon' },
  { code: '430', label: 'German Language' },
  { code: '440', label: 'French' },
  { code: '450', label: 'Italian, Rumanian' },
  { code: '460', label: 'Spanish, Portuguese' },
  { code: '470', label: 'Latin and Other Italic Languages' },
  { code: '480', label: 'Classical and Modern Greek' },
  { code: '490', label: 'Other Languages' },
  { code: '500', label: 'SCIENCE' },
  { code: '510', label: 'Mathematics' },
  { code: '520', label: 'Astronomy' },
  { code: '530', label: 'Physics' },
  { code: '540', label: 'Chemistry' },
  { code: '550', label: 'Earth Sciences' },
  { code: '560', label: 'Paleontology' },
  { code: '570', label: 'Life Sciences' },
  { code: '580', label: 'Botanical Sciences' },
  { code: '590', label: 'Zoological Sciences' },
  { code: '600', label: 'TECHNOLOGY' },
  { code: '610', label: 'Medical Sciences' },
  { code: '620', label: 'Engineering' },
  { code: '630', label: 'Agriculture' },
  { code: '640', label: 'Domestic Sciences' },
  { code: '650', label: 'Business and Management' },
  { code: '660', label: 'Chemical Technology' },
  { code: '670', label: 'Manufacturers' },
  { code: '690', label: 'Building Construction' },
  { code: '700', label: 'THE ARTS' },
  { code: '710', label: 'Landscape and Civic Art' },
  { code: '720', label: 'Architecture' },
  { code: '730', label: 'Sculpture, Plastics' },
  { code: '740', label: 'Drawing, Decorative Arts' },
  { code: '750', label: 'Painting' },
  { code: '760', label: 'Prints and Print Making' },
  { code: '770', label: 'Photography' },
  { code: '780', label: 'Music' },
  { code: '790', label: 'Recreation, Performing Arts' },
  { code: '800', label: 'LITERATURE' },
  { code: '810', label: 'American Literature' },
  { code: '820', label: 'English Literature' },
  { code: '830', label: 'German Literature' },
  { code: '840', label: 'French Literature' },
  { code: '850', label: 'Italian, Rumanian Literature' },
  { code: '860', label: 'Spanish, Portuguese Literature' },
  { code: '870', label: 'Latin and Other Italic Literatures' },
  { code: '880', label: 'Classical and Modern Greek Literature' },
  { code: '890', label: 'Other Literature' },
  { code: '900', label: 'HISTORY, GEOGRAPHY' },
  { code: '910', label: 'Geography, Travel' },
  { code: '920', label: 'Biography, Genealogy' },
  { code: '930', label: 'Ancient History' },
  { code: '940', label: 'Europe' },
  { code: '950', label: 'Asia' },
  { code: '960', label: 'Africa' },
  { code: '970', label: 'North America' },
  { code: '980', label: 'South America' },
  { code: '990', label: 'Pacific Ocean Islands' },
  { code: '991', label: 'Indonesia' },
  { code: '993', label: 'New Zealand and Melanesia' },
  { code: '994', label: 'Australia' },
  { code: '995', label: 'New Guinea (Papua)' },
  { code: '996', label: 'Polynesia' },
  { code: '997', label: 'Atlantic Ocean Islands' },
  { code: '998', label: 'Arctic Region' },
  { code: '999', label: 'Antarctic Regions' }
];

export const formatDeweyDisplay = ({ code, label }) => `${code} ${label}`;
